version: '3'
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
    ports:
      - "8000:9000"
      - "9123:8123"
    # network_mode: host
    # cap_add:
    #   - SYS_NICE
    #   - NET_ADMIN
    #   - IPC_LOCK

    #   - SYS_PTRACE
    networks:
      - ch_network

networks:
  ch_network:
    driver: bridge